//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class scmsEntities : DbContext
    {
        public scmsEntities()
            : base("name=scmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<club> club { get; set; }
        public DbSet<clubactivity> clubactivity { get; set; }
        public DbSet<clubmanager> clubmanager { get; set; }
        public DbSet<clubmember> clubmember { get; set; }
        public DbSet<comment> comment { get; set; }
        public DbSet<newclub> newclub { get; set; }
        public DbSet<newmember> newmember { get; set; }
        public DbSet<teacher> teacher { get; set; }
        public DbSet<user> user { get; set; }
    }
}
